main: eu.decentsoftware.holograms.plugin.DecentHologramsPlugin
api-version: 1.13
softdepend: [PlaceholderAPI]
name: DecentHolograms
description: Lightweight but powerful hologram plugin with many features and configuration options.
<<<<<<< Updated upstream
version: '${version}'
=======
version: ${version}
>>>>>>> Stashed changes
author: d0by

commands:
  decentholograms:
    aliases: [dh, holograms, hologram, holo]
    usage: /decentholograms <args>
    description: The main command of DecentHolograms plugin.
